# Generated by Django 6.1.1 on 2026-09-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='dealer',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dealer',
            name='long',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='dealer',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='dealer',
            name='st',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
